// Code generated by scripts/codegen.py. DO NOT EDIT.

package shinemonitor

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
)

var _ = strings.Builder{} // force import even if no string params
var _ = fmt.Sprintf       // ditto
var _ context.Context     // ditto

// UpdateToken calls the vendor action `updateToken` (chapter 2).
// Vendor docs: https://api.shinemonitor.com/chapter2/updateToken.html
func (c *Client) UpdateToken(ctx context.Context) (json.RawMessage, error) {
	var extra strings.Builder
	return c.requestWith(ctx, "updateToken", extra.String())
}

// QueryAccountInfo calls the vendor action `queryAccountInfo` (chapter 2).
// Vendor docs: https://api.shinemonitor.com/chapter2/queryAccountInfo.html
func (c *Client) QueryAccountInfo(ctx context.Context) (json.RawMessage, error) {
	var extra strings.Builder
	return c.requestWith(ctx, "queryAccountInfo", extra.String())
}

// UpdatePassword calls the vendor action `updatePassword` (chapter 2).
// Vendor docs: https://api.shinemonitor.com/chapter2/updatePassword.html
func (c *Client) UpdatePassword(ctx context.Context, oldPwd string, newPwd string) (json.RawMessage, error) {
	var extra strings.Builder
	extra.WriteString(fmt.Sprintf("&oldPwd=%s", oldPwd))
	extra.WriteString(fmt.Sprintf("&newPwd=%s", newPwd))
	return c.requestWith(ctx, "updatePassword", extra.String())
}

// QueryPlants calls the vendor action `queryPlants` (chapter 3).
// Vendor docs: https://api.shinemonitor.com/chapter3/queryPlants.html
func (c *Client) QueryPlants(ctx context.Context, status *int64, orderBy *string, plantName *string, page *int64, pagesize *int64) (json.RawMessage, error) {
	var extra strings.Builder
	if status != nil {
		extra.WriteString(fmt.Sprintf("&status=%v", *status))
	}
	if orderBy != nil {
		extra.WriteString(fmt.Sprintf("&orderBy=%s", *orderBy))
	}
	if plantName != nil {
		extra.WriteString(fmt.Sprintf("&plantName=%s", *plantName))
	}
	if page != nil {
		extra.WriteString(fmt.Sprintf("&page=%v", *page))
	}
	if pagesize != nil {
		extra.WriteString(fmt.Sprintf("&pagesize=%v", *pagesize))
	}
	return c.requestWith(ctx, "queryPlants", extra.String())
}

// QueryPlantInfo calls the vendor action `queryPlantInfo` (chapter 3).
// Vendor docs: https://api.shinemonitor.com/chapter3/queryPlantInfo.html
func (c *Client) QueryPlantInfo(ctx context.Context, plantid int64) (json.RawMessage, error) {
	var extra strings.Builder
	extra.WriteString(fmt.Sprintf("&plantid=%v", plantid))
	return c.requestWith(ctx, "queryPlantInfo", extra.String())
}

// QueryPlantCount calls the vendor action `queryPlantCount` (chapter 3).
// Vendor docs: https://api.shinemonitor.com/chapter3/queryPlantCount.html
func (c *Client) QueryPlantCount(ctx context.Context) (json.RawMessage, error) {
	var extra strings.Builder
	return c.requestWith(ctx, "queryPlantCount", extra.String())
}

// QueryPlantEnergyDay calls the vendor action `queryPlantEnergyDay` (chapter 3).
// Vendor docs: https://api.shinemonitor.com/chapter3/queryPlantEnergyDay.html
func (c *Client) QueryPlantEnergyDay(ctx context.Context, plantid int64, date string) (json.RawMessage, error) {
	var extra strings.Builder
	extra.WriteString(fmt.Sprintf("&plantid=%v", plantid))
	extra.WriteString(fmt.Sprintf("&date=%s", date))
	return c.requestWith(ctx, "queryPlantEnergyDay", extra.String())
}

// QueryPlantEnergyMonth calls the vendor action `queryPlantEnergyMonth` (chapter 3).
// Vendor docs: https://api.shinemonitor.com/chapter3/queryPlantEnergyMonth.html
func (c *Client) QueryPlantEnergyMonth(ctx context.Context, plantid int64, date string) (json.RawMessage, error) {
	var extra strings.Builder
	extra.WriteString(fmt.Sprintf("&plantid=%v", plantid))
	extra.WriteString(fmt.Sprintf("&date=%s", date))
	return c.requestWith(ctx, "queryPlantEnergyMonth", extra.String())
}

// QueryPlantEnergyYear calls the vendor action `queryPlantEnergyYear` (chapter 3).
// Vendor docs: https://api.shinemonitor.com/chapter3/queryPlantEnergyYear.html
func (c *Client) QueryPlantEnergyYear(ctx context.Context, plantid int64, date string) (json.RawMessage, error) {
	var extra strings.Builder
	extra.WriteString(fmt.Sprintf("&plantid=%v", plantid))
	extra.WriteString(fmt.Sprintf("&date=%s", date))
	return c.requestWith(ctx, "queryPlantEnergyYear", extra.String())
}

// QueryPlantEnergyTotal calls the vendor action `queryPlantEnergyTotal` (chapter 3).
// Vendor docs: https://api.shinemonitor.com/chapter3/queryPlantEnergyTotal.html
func (c *Client) QueryPlantEnergyTotal(ctx context.Context, plantid int64) (json.RawMessage, error) {
	var extra strings.Builder
	extra.WriteString(fmt.Sprintf("&plantid=%v", plantid))
	return c.requestWith(ctx, "queryPlantEnergyTotal", extra.String())
}

// QueryPlantActiveOuputPowerCurrent calls the vendor action `queryPlantActiveOuputPowerCurrent` (chapter 3).
// Vendor docs: https://api.shinemonitor.com/chapter3/queryPlantActiveOuputPowerCurrent.html
func (c *Client) QueryPlantActiveOuputPowerCurrent(ctx context.Context, plantid int64) (json.RawMessage, error) {
	var extra strings.Builder
	extra.WriteString(fmt.Sprintf("&plantid=%v", plantid))
	return c.requestWith(ctx, "queryPlantActiveOuputPowerCurrent", extra.String())
}

// QueryCollectors calls the vendor action `queryCollectors` (chapter 4).
// Vendor docs: https://api.shinemonitor.com/chapter4/queryCollectors.html
func (c *Client) QueryCollectors(ctx context.Context, page *int64, pagesize *int64) (json.RawMessage, error) {
	var extra strings.Builder
	if page != nil {
		extra.WriteString(fmt.Sprintf("&page=%v", *page))
	}
	if pagesize != nil {
		extra.WriteString(fmt.Sprintf("&pagesize=%v", *pagesize))
	}
	return c.requestWith(ctx, "queryCollectors", extra.String())
}

// QueryCollectorInfo calls the vendor action `queryCollectorInfo` (chapter 4).
// Vendor docs: https://api.shinemonitor.com/chapter4/queryCollectorInfo.html
func (c *Client) QueryCollectorInfo(ctx context.Context, pn string) (json.RawMessage, error) {
	var extra strings.Builder
	extra.WriteString(fmt.Sprintf("&pn=%s", pn))
	return c.requestWith(ctx, "queryCollectorInfo", extra.String())
}

// QueryCollectorStatus calls the vendor action `queryCollectorStatus` (chapter 4).
// Vendor docs: https://api.shinemonitor.com/chapter4/queryCollectorStatus.html
func (c *Client) QueryCollectorStatus(ctx context.Context, pn string) (json.RawMessage, error) {
	var extra strings.Builder
	extra.WriteString(fmt.Sprintf("&pn=%s", pn))
	return c.requestWith(ctx, "queryCollectorStatus", extra.String())
}

// QueryCollectorDevices calls the vendor action `queryCollectorDevices` (chapter 4).
// Vendor docs: https://api.shinemonitor.com/chapter4/queryCollectorDevices.html
func (c *Client) QueryCollectorDevices(ctx context.Context, pn string) (json.RawMessage, error) {
	var extra strings.Builder
	extra.WriteString(fmt.Sprintf("&pn=%s", pn))
	return c.requestWith(ctx, "queryCollectorDevices", extra.String())
}

// QueryDevices calls the vendor action `queryDevices` (chapter 5).
// Vendor docs: https://api.shinemonitor.com/chapter5/queryDevices.html
func (c *Client) QueryDevices(ctx context.Context, page *int64, pagesize *int64) (json.RawMessage, error) {
	var extra strings.Builder
	if page != nil {
		extra.WriteString(fmt.Sprintf("&page=%v", *page))
	}
	if pagesize != nil {
		extra.WriteString(fmt.Sprintf("&pagesize=%v", *pagesize))
	}
	return c.requestWith(ctx, "queryDevices", extra.String())
}

func (c *Client) WebQueryDeviceEs(ctx context.Context) (json.RawMessage, error) {
	var extra strings.Builder
	return c.requestWith(ctx, "webQueryDeviceEs", extra.String())
}

// QueryDeviceCount calls the vendor action `queryDeviceCount` (chapter 5).
// Vendor docs: https://api.shinemonitor.com/chapter5/queryDeviceCount.html
func (c *Client) QueryDeviceCount(ctx context.Context) (json.RawMessage, error) {
	var extra strings.Builder
	return c.requestWith(ctx, "queryDeviceCount", extra.String())
}

// QueryDeviceInfo calls the vendor action `queryDeviceInfo` (chapter 5).
// Vendor docs: https://api.shinemonitor.com/chapter5/queryDeviceInfo.html
func (c *Client) QueryDeviceInfo(ctx context.Context, pn string, devcode int64, devaddr int64, sn string) (json.RawMessage, error) {
	var extra strings.Builder
	extra.WriteString(fmt.Sprintf("&pn=%s", pn))
	extra.WriteString(fmt.Sprintf("&devcode=%v", devcode))
	extra.WriteString(fmt.Sprintf("&devaddr=%v", devaddr))
	extra.WriteString(fmt.Sprintf("&sn=%s", sn))
	return c.requestWith(ctx, "queryDeviceInfo", extra.String())
}

// QueryDeviceLastData calls the vendor action `queryDeviceLastData` (chapter 5).
// Vendor docs: https://api.shinemonitor.com/chapter5/queryDeviceLastData.html
func (c *Client) QueryDeviceLastData(ctx context.Context, pn string, devcode int64, devaddr int64, sn string) (json.RawMessage, error) {
	var extra strings.Builder
	extra.WriteString(fmt.Sprintf("&pn=%s", pn))
	extra.WriteString(fmt.Sprintf("&devcode=%v", devcode))
	extra.WriteString(fmt.Sprintf("&devaddr=%v", devaddr))
	extra.WriteString(fmt.Sprintf("&sn=%s", sn))
	return c.requestWith(ctx, "queryDeviceLastData", extra.String())
}

func (c *Client) QuerySPDeviceLastData(ctx context.Context, pn string, devcode int64, devaddr int64, sn string) (json.RawMessage, error) {
	var extra strings.Builder
	extra.WriteString(fmt.Sprintf("&pn=%s", pn))
	extra.WriteString(fmt.Sprintf("&devcode=%v", devcode))
	extra.WriteString(fmt.Sprintf("&devaddr=%v", devaddr))
	extra.WriteString(fmt.Sprintf("&sn=%s", sn))
	return c.requestWith(ctx, "querySPDeviceLastData", extra.String())
}

// QueryDeviceDataOneDay calls the vendor action `queryDeviceDataOneDay` (chapter 5).
// Vendor docs: https://api.shinemonitor.com/chapter5/queryDeviceDataOneDay.html
func (c *Client) QueryDeviceDataOneDay(ctx context.Context, pn string, devcode int64, devaddr int64, sn string, date string) (json.RawMessage, error) {
	var extra strings.Builder
	extra.WriteString(fmt.Sprintf("&pn=%s", pn))
	extra.WriteString(fmt.Sprintf("&devcode=%v", devcode))
	extra.WriteString(fmt.Sprintf("&devaddr=%v", devaddr))
	extra.WriteString(fmt.Sprintf("&sn=%s", sn))
	extra.WriteString(fmt.Sprintf("&date=%s", date))
	return c.requestWith(ctx, "queryDeviceDataOneDay", extra.String())
}

// QueryDeviceStatus calls the vendor action `queryDeviceStatus` (chapter 5).
// Vendor docs: https://api.shinemonitor.com/chapter5/queryDeviceStatus.html
func (c *Client) QueryDeviceStatus(ctx context.Context, pn string, devcode int64, devaddr int64, sn string) (json.RawMessage, error) {
	var extra strings.Builder
	extra.WriteString(fmt.Sprintf("&pn=%s", pn))
	extra.WriteString(fmt.Sprintf("&devcode=%v", devcode))
	extra.WriteString(fmt.Sprintf("&devaddr=%v", devaddr))
	extra.WriteString(fmt.Sprintf("&sn=%s", sn))
	return c.requestWith(ctx, "queryDeviceStatus", extra.String())
}

// QueryDeviceWarning calls the vendor action `queryDeviceWarning` (chapter 5).
// Vendor docs: https://api.shinemonitor.com/chapter5/queryDeviceWarning.html
func (c *Client) QueryDeviceWarning(ctx context.Context, pn string, devcode int64, devaddr int64, sn string) (json.RawMessage, error) {
	var extra strings.Builder
	extra.WriteString(fmt.Sprintf("&pn=%s", pn))
	extra.WriteString(fmt.Sprintf("&devcode=%v", devcode))
	extra.WriteString(fmt.Sprintf("&devaddr=%v", devaddr))
	extra.WriteString(fmt.Sprintf("&sn=%s", sn))
	return c.requestWith(ctx, "queryDeviceWarning", extra.String())
}

// QueryDeviceCtrlField calls the vendor action `queryDeviceCtrlField` (chapter 5).
// Vendor docs: https://api.shinemonitor.com/chapter5/queryDeviceCtrlField.html
func (c *Client) QueryDeviceCtrlField(ctx context.Context, pn string, devcode int64, devaddr int64, sn string) (json.RawMessage, error) {
	var extra strings.Builder
	extra.WriteString(fmt.Sprintf("&pn=%s", pn))
	extra.WriteString(fmt.Sprintf("&devcode=%v", devcode))
	extra.WriteString(fmt.Sprintf("&devaddr=%v", devaddr))
	extra.WriteString(fmt.Sprintf("&sn=%s", sn))
	return c.requestWith(ctx, "queryDeviceCtrlField", extra.String())
}

// QueryDeviceCtrlValue calls the vendor action `queryDeviceCtrlValue` (chapter 5).
// Vendor docs: https://api.shinemonitor.com/chapter5/queryDeviceCtrlValue.html
func (c *Client) QueryDeviceCtrlValue(ctx context.Context, pn string, devcode int64, devaddr int64, sn string, id string) (json.RawMessage, error) {
	var extra strings.Builder
	extra.WriteString(fmt.Sprintf("&pn=%s", pn))
	extra.WriteString(fmt.Sprintf("&devcode=%v", devcode))
	extra.WriteString(fmt.Sprintf("&devaddr=%v", devaddr))
	extra.WriteString(fmt.Sprintf("&sn=%s", sn))
	extra.WriteString(fmt.Sprintf("&id=%s", id))
	return c.requestWith(ctx, "queryDeviceCtrlValue", extra.String())
}

// CtrlDevice calls the vendor action `ctrlDevice` (chapter 5).
// Vendor docs: https://api.shinemonitor.com/chapter5/ctrlDevice.html
func (c *Client) CtrlDevice(ctx context.Context, pn string, devcode int64, devaddr int64, sn string, id string, val string) (json.RawMessage, error) {
	var extra strings.Builder
	extra.WriteString(fmt.Sprintf("&pn=%s", pn))
	extra.WriteString(fmt.Sprintf("&devcode=%v", devcode))
	extra.WriteString(fmt.Sprintf("&devaddr=%v", devaddr))
	extra.WriteString(fmt.Sprintf("&sn=%s", sn))
	extra.WriteString(fmt.Sprintf("&id=%s", id))
	extra.WriteString(fmt.Sprintf("&val=%s", val))
	return c.requestWith(ctx, "ctrlDevice", extra.String())
}

// QueryDeviceEnergyDay calls the vendor action `queryDeviceEnergyDay` (chapter 6).
// Vendor docs: https://api.shinemonitor.com/chapter6/queryDeviceEnergyDay.html
func (c *Client) QueryDeviceEnergyDay(ctx context.Context, pn string, devcode int64, devaddr int64, sn string, date string) (json.RawMessage, error) {
	var extra strings.Builder
	extra.WriteString(fmt.Sprintf("&pn=%s", pn))
	extra.WriteString(fmt.Sprintf("&devcode=%v", devcode))
	extra.WriteString(fmt.Sprintf("&devaddr=%v", devaddr))
	extra.WriteString(fmt.Sprintf("&sn=%s", sn))
	extra.WriteString(fmt.Sprintf("&date=%s", date))
	return c.requestWith(ctx, "queryDeviceEnergyDay", extra.String())
}

// QueryDeviceEnergyMonth calls the vendor action `queryDeviceEnergyMonth` (chapter 6).
// Vendor docs: https://api.shinemonitor.com/chapter6/queryDeviceEnergyMonth.html
func (c *Client) QueryDeviceEnergyMonth(ctx context.Context, pn string, devcode int64, devaddr int64, sn string, date string) (json.RawMessage, error) {
	var extra strings.Builder
	extra.WriteString(fmt.Sprintf("&pn=%s", pn))
	extra.WriteString(fmt.Sprintf("&devcode=%v", devcode))
	extra.WriteString(fmt.Sprintf("&devaddr=%v", devaddr))
	extra.WriteString(fmt.Sprintf("&sn=%s", sn))
	extra.WriteString(fmt.Sprintf("&date=%s", date))
	return c.requestWith(ctx, "queryDeviceEnergyMonth", extra.String())
}

// QueryDeviceEnergyYear calls the vendor action `queryDeviceEnergyYear` (chapter 6).
// Vendor docs: https://api.shinemonitor.com/chapter6/queryDeviceEnergyYear.html
func (c *Client) QueryDeviceEnergyYear(ctx context.Context, pn string, devcode int64, devaddr int64, sn string, date string) (json.RawMessage, error) {
	var extra strings.Builder
	extra.WriteString(fmt.Sprintf("&pn=%s", pn))
	extra.WriteString(fmt.Sprintf("&devcode=%v", devcode))
	extra.WriteString(fmt.Sprintf("&devaddr=%v", devaddr))
	extra.WriteString(fmt.Sprintf("&sn=%s", sn))
	extra.WriteString(fmt.Sprintf("&date=%s", date))
	return c.requestWith(ctx, "queryDeviceEnergyYear", extra.String())
}

// QueryDeviceEnergyTotal calls the vendor action `queryDeviceEnergyTotal` (chapter 6).
// Vendor docs: https://api.shinemonitor.com/chapter6/queryDeviceEnergyTotal.html
func (c *Client) QueryDeviceEnergyTotal(ctx context.Context, pn string, devcode int64, devaddr int64, sn string) (json.RawMessage, error) {
	var extra strings.Builder
	extra.WriteString(fmt.Sprintf("&pn=%s", pn))
	extra.WriteString(fmt.Sprintf("&devcode=%v", devcode))
	extra.WriteString(fmt.Sprintf("&devaddr=%v", devaddr))
	extra.WriteString(fmt.Sprintf("&sn=%s", sn))
	return c.requestWith(ctx, "queryDeviceEnergyTotal", extra.String())
}

// QueryDeviceActiveOuputPowerCurrent calls the vendor action `queryDeviceActiveOuputPowerCurrent` (chapter 6).
// Vendor docs: https://api.shinemonitor.com/chapter6/queryDeviceActiveOuputPowerCurrent.html
func (c *Client) QueryDeviceActiveOuputPowerCurrent(ctx context.Context, pn string, devcode int64, devaddr int64, sn string) (json.RawMessage, error) {
	var extra strings.Builder
	extra.WriteString(fmt.Sprintf("&pn=%s", pn))
	extra.WriteString(fmt.Sprintf("&devcode=%v", devcode))
	extra.WriteString(fmt.Sprintf("&devaddr=%v", devaddr))
	extra.WriteString(fmt.Sprintf("&sn=%s", sn))
	return c.requestWith(ctx, "queryDeviceActiveOuputPowerCurrent", extra.String())
}

// QueryCameraInfo calls the vendor action `queryCameraInfo` (chapter 11).
// Vendor docs: https://api.shinemonitor.com/chapter11/queryCameraInfo.html
func (c *Client) QueryCameraInfo(ctx context.Context, cameraid int64) (json.RawMessage, error) {
	var extra strings.Builder
	extra.WriteString(fmt.Sprintf("&cameraid=%v", cameraid))
	return c.requestWith(ctx, "queryCameraInfo", extra.String())
}

// UploadImg calls the vendor action `uploadImg` (chapter 84).
// Vendor docs: https://api.shinemonitor.com/chapter84/uploadImg.html
func (c *Client) UploadImg(ctx context.Context, fmt_ string) (json.RawMessage, error) {
	var extra strings.Builder
	extra.WriteString(fmt.Sprintf("&fmt=%s", fmt_))
	return c.requestWith(ctx, "uploadImg", extra.String())
}
